### ISSUE TITLE
Protect classes against self-assignment

### ISSUE THREAD

**Issue by elfring** [kakao/n2#10]
The class “Hnsw” contains [a custom copy assignment operator](https://github.com/kakao/n2/blob/f3133218a200695b8e11d9513aad0a8bbd87e0d5/src/hnsw.cc#L136 "Update candidate: Hnsw::operator=()").
I wonder why [a check against self-assignment](https://isocpp.org/wiki/faq/assignment-operators#self-assignment-how "How do I handle self-assignment?") was omitted.

**Comment by corona10** [comment]
@elfring Yes, you are right. That's my fault. Can you send the patch to solve this issue?

**Comment by elfring** [comment]
Are you quicker than me adding another if statement (if it is really needed) in the affected function implementation?

**Comment by corona10** [comment]
@elfring 
I can patch this right now, but if you want to patch, I can wait for your patch. :)

**Comment by elfring** [comment]
You do not need to wait on me for this adjustment.

**Comment by gony-lee** [comment]
Patched in N2 version 0.1.6
