### ISSUE TITLE
Online update support

### ISSUE THREAD

**Issue by qingyuanxingsi** [kakao/n2#25]
Awesome project, can **n2** support online addition of vectors??

**Comment by corona10** [comment]
N2 does not support online index updating.

**Comment by chasingegg** [comment]
N2 is based on HNSW, actually hnsw supports online index updating, so can I say it is just not implemented, the feature of online index updating is possible to be added?

**Comment by gony-lee** [comment]
@chasingegg Online update is not possible in the current architecture, not a function that has not been implemented. The reason for this is impossible, after building the hnsw graph, packing the graph into a model(one large contiguous memory data) for efficiency and updating the graph with only the model is neither easy nor efficient.
