### ISSUE TITLE
Python bindings to static library

### ISSUE THREAD

**Issue by aagnone3** [kakao/n2#27]
Is it possible to create python bindings to a statically-compiled version of the library? The end goal is to compile this on a valid machine and then use the library on a machine which does not have c++11. Alternatively, I could bring in a version of c++11, I'm just pretty unfamiliar with python <-> c++ bindings.

**Comment by gony-lee** [comment]
If N2 supports bdist(built distribution), you can use it without c++ build environment. However, N2 only uses sdist(source distribution), not bdist method, for performance. 
it is recommended to use it in a c++14 buildable environment.
