### ISSUE TITLE
With the same accuracy, the number of comparisons with the paper is very different.

### ISSUE THREAD

**Issue by MartinNum** [kakao/n2#31]
In the case of 90% accuracy, the paper only needs to compare hundreds of times, why is your code compared thousands of times?

**Comment by gony-lee** [comment]
Could you tell me the dataset and n2 parameter you used? and I wonder how you measured the number of comparisons.

**Comment by MartinNum** [comment]
> Could you tell me the dataset and n2 parameter you used? and I wonder how you measured the number of comparisons.

It’s my problem. The random dataset I used resulted in a high number of comparisons. After using the dataset SIFT1M, the comparison times became normal.

**Comment by gony-lee** [comment]
Sorry for the late feedback, we will close the issue.
