### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [kakao/n2#9]
Would you like to [wrap any pointer data members](https://github.com/kakao/n2/blob/f3133218a200695b8e11d9513aad0a8bbd87e0d5/src/hnsw.cc#L83 "Update candidate: Hnsw class") with the template class “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by corona10** [comment]
@elfring 
Yes, I'd love to, Can you send the patch for this issue also? I definitely agree with your opinion.

**Comment by gony-lee** [comment]
Patched in N2 version 0.1.6
